version: '3.5'

services:

  webapp:
    image: krepsjan/opendcim
# Sem lze i predepsat ten Dockerfile a pripadny tag. 
    build: .
    env_file: .env
    environment:
      OPENDCIM_DB_HOST: db
      OPENDCIM_DB_NAME: ${MYSQL_USER}
      OPENDCIM_DB_USER: ${MYSQL_USER}
      OPENDCIM_DB_PASS: ${MYSQL_PASSWORD}
    volumes:
       - ./dcim_data:/data
#      - dcim_data:/data
#      - ./certs:/certs
    networks:
      - database_net
      - outside
    ports:
      - ${DCIM_HTTP_PORT}:80
      - ${DCIM_HTTPS_PORT}:443
    restart: always
    depends_on:
      - db
        # condition: service_healthy
        # restart: true


  db:
    image: mariadb:10.2.14
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    restart: always
    env_file: .env
    volumes:
      - dcim_db:/var/lib/mysql
    networks:
      - database_net
    # test: 
    # healthcheck:
    #   test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    #   start_period: 10s
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

# adminer tady nepotrebuju, to mohu nechat standalone
# Ale v me instalaci vzdy chci databazi, proto to sloucim.

networks:
  database_net:
    driver: bridge
    internal: true
  outside:
    driver: bridge

volumes:
  dcim_data:
    driver: local

  dcim_db:
    driver: local

